OUTLINE_TAG: str = "outline"
CATEGORY: str = "category"
DISABLED: str = "isComment"
HTML_URL: str = "htmlUrl"
RSS: str = "rss"
TEXT: str = "text"
TITLE: str = "title"
TYPE: str = "type"
XML_URL: str = "xmlUrl"
DATE_CREATED: str = "dateCreated"
DATE_MODIFIED: str = "dateModified"

TRUE: str = "true"
FALSE: str = "false"